version: "3"

tasks:
  build:
    desc: Build all project packages
    cmds:
      - go build ./...
  run:
    desc: run all project packages for dev
    cmds:
      - go run ./...
  test:
    desc: Run the test suite
    cmds:
      - go test ./...
  vet:
    desc: Run Go's static analyzer
    cmds:
      - go vet ./...
